from typing import Dict
from .schemas import FieldInterpretation

CATALOG: Dict[str, FieldInterpretation] = {
    # Group: DSEI / territorial planning
    "distrito_sanitario_especial_indigena_dsei": FieldInterpretation(
        field_name="distrito_sanitario_especial_indigena_dsei",
        group="DSEI / territorial planning",
        priority="very_high",
        why_it_matters="Defines the territorial unit for planning.",
        how_it_guides_plan="Use this to generate recommendations by DSEI and connect actions to DSEI, municipality, AIS, AISAN, village leadership and local health teams.",
        dengue_relevance="governance",
        is_direct_dengue_risk=False,
        is_governance_field=True
    ),
    "distrito_sanitario_especial_indigena": FieldInterpretation(
        field_name="distrito_sanitario_especial_indigena",
        group="DSEI / territorial planning",
        priority="very_high",
        why_it_matters="Defines the territorial planning unit.",
        how_it_guides_plan="Generate actions by DSEI and assign responsibility to DSEI, SESAI, municipality, AIS, AISAN, local leadership and sanitation teams.",
        dengue_relevance="governance",
        is_direct_dengue_risk=False,
        is_governance_field=True
    ),
    # Group: solid waste governance and dengue-relevant containers
    "coleta_e_destinacao_de_residuos_solidos_percentual_de_aldeias_onde_a_prefeitura_e_a_principal_responsavel": FieldInterpretation(
        field_name="coleta_e_destinacao_de_residuos_solidos_percentual_de_aldeias_onde_a_prefeitura_e_a_principal_responsavel",
        group="solid waste governance and dengue-relevant containers",
        priority="very_high",
        why_it_matters="Shows whether the municipality is already the main actor in waste collection.",
        how_it_guides_plan="If high, involve municipal cleaning services, collection schedule, emergency mutirões and formal agreements with the DSEI.",
        dengue_relevance="governance",
        is_direct_dengue_risk=False,
        is_governance_field=True
    ),
    "coleta_e_destinacao_de_residuos_solidos_percentual_de_aldeias_onde_o_dsei_e_o_principal_responsavel": FieldInterpretation(
        field_name="coleta_e_destinacao_de_residuos_solidos_percentual_de_aldeias_onde_o_dsei_e_o_principal_responsavel",
        group="solid waste governance and dengue-relevant containers",
        priority="high",
        why_it_matters="Shows whether the DSEI itself has operational responsibility.",
        how_it_guides_plan="If high, direct actions to DSEI logistics, sanitation teams, AISAN and Indigenous health infrastructure.",
        dengue_relevance="governance",
        is_direct_dengue_risk=False,
        is_governance_field=True
    ),
    "coleta_e_destinacao_de_residuos_solidos_percentual_de_aldeias_onde_a_propria_aldeia_e_a_principal_responsavel": FieldInterpretation(
        field_name="coleta_e_destinacao_de_residuos_solidos_percentual_de_aldeias_onde_a_propria_aldeia_e_a_principal_responsavel",
        group="solid waste governance and dengue-relevant containers",
        priority="high",
        why_it_matters="Indicates community self-management of waste.",
        how_it_guides_plan="Avoid blaming the community. Propose supported community-led actions such as tools, bags, transport, collection points and participatory planning.",
        dengue_relevance="governance",
        is_direct_dengue_risk=False,
        is_governance_field=True
    ),
    "coleta_e_destinacao_de_residuos_solidos_percentual_de_aldeias_onde_nao_ha_informacao_sobre_os_responsaveis": FieldInterpretation(
        field_name="coleta_e_destinacao_de_residuos_solidos_percentual_de_aldeias_onde_nao_ha_informacao_sobre_os_responsaveis",
        group="solid waste governance and dengue-relevant containers",
        priority="very_high",
        why_it_matters="Missing responsibility is an operational risk.",
        how_it_guides_plan="The first intervention must include data validation: map responsibility village by village with leaders, AIS/AISAN, DSEI and municipality.",
        dengue_relevance="data_quality",
        is_direct_dengue_risk=False,
        is_governance_field=True,
        requires_local_validation_when_missing=True
    ),
    "possui_coleta_seletiva_implantada_percentual_de_aldeias_que_nao_possuem_coleta_seletiva": FieldInterpretation(
        field_name="possui_coleta_seletiva_implantada_percentual_de_aldeias_que_nao_possuem_coleta_seletiva",
        group="solid waste governance and dengue-relevant containers",
        priority="very_high",
        why_it_matters="Without selective collection, bottles, cans, plastics, packaging and other containers may remain exposed.",
        how_it_guides_plan="Generate actions such as temporary collection points for recyclables, removal of containers before rainy periods and partnerships with municipal cleaning or recycling programs.",
        dengue_relevance="direct",
        is_direct_dengue_risk=True,
        is_governance_field=False
    ),
    "possui_coleta_seletiva_implantada_percentual_de_aldeias_que_possuem_coleta_seletiva": FieldInterpretation(
        field_name="possui_coleta_seletiva_implantada_percentual_de_aldeias_que_possuem_coleta_seletiva",
        group="solid waste governance and dengue-relevant containers",
        priority="medium_high",
        why_it_matters="Shows existing structure that can be strengthened.",
        how_it_guides_plan="If present, reinforce current selective collection instead of creating a new process.",
        dengue_relevance="direct",
        is_direct_dengue_risk=True,
        is_governance_field=False
    ),
    "logistica_reversa_percentual_de_aldeias_que_realizam_logistica_reserva": FieldInterpretation(
        field_name="logistica_reversa_percentual_de_aldeias_que_realizam_logistica_reserva",
        group="solid waste governance and dengue-relevant containers",
        priority="very_high",
        why_it_matters="Reverse logistics is important for tires, bottles, containers and other hard-to-dispose materials. Tires and containers can become breeding sites.",
        how_it_guides_plan="If low or zero, include collection campaigns for tires, plastic containers and scrap, with municipality and private-sector responsibility when applicable.",
        dengue_relevance="direct",
        is_direct_dengue_risk=True,
        is_governance_field=False
    ),
    "possui_vala_construida_pela_comunidade_percentual_de_aldeias_com_presenca_de_valas_construidas_pela_comunidade": FieldInterpretation(
        field_name="possui_vala_construida_pela_comunidade_percentual_de_aldeias_com_presenca_de_valas_construidas_pela_comunidade",
        group="solid waste governance and dengue-relevant containers",
        priority="medium_high",
        why_it_matters="Ditches are not the classic main breeding site for Aedes, but they indicate drainage/sanitation problems and possible stagnant water.",
        how_it_guides_plan="Include inspection of stagnant water, cleaning, drainage correction and safe alternatives, without assuming every ditch is an Aedes focus.",
        dengue_relevance="indirect",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "pratica_de_queima_de_residuos_pela_comunidade_percentual_de_aldeias_que_possuem_a_pratica_de_queima_dos_residuos": FieldInterpretation(
        field_name="pratica_de_queima_de_residuos_pela_comunidade_percentual_de_aldeias_que_possuem_a_pratica_de_queima_dos_residuos",
        group="solid waste governance and dengue-relevant containers",
        priority="high",
        why_it_matters="Burning waste often signals lack of regular collection or lack of disposal alternatives. It should not be recommended as a dengue solution.",
        how_it_guides_plan="Propose realistic alternatives: scheduled waste removal, safe storage until collection, community containers and negotiation with municipal services.",
        dengue_relevance="vulnerability",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "pratica_de_queima_de_residuos_pela_comunidade_percentual_de_aldeias_que_nao_possuem_a_pratica_de_queima_dos_residuos": FieldInterpretation(
        field_name="pratica_de_queima_de_residuos_pela_comunidade_percentual_de_aldeias_que_nao_possuem_a_pratica_de_queima_dos_residuos",
        group="solid waste governance and dengue-relevant containers",
        priority="medium",
        why_it_matters="Shows where waste burning is not common.",
        how_it_guides_plan="Focus on maintaining safer practices and preventing accumulation of containers.",
        dengue_relevance="vulnerability",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    
    # Group: sewage and sanitation infrastructure
    "exist_estrut_perc_ald_banheiro_particular": FieldInterpretation(
        field_name="exist_estrut_perc_ald_banheiro_particular",
        group="sewage and sanitation infrastructure",
        priority="high",
        why_it_matters="Indicates household-level sanitation infrastructure.",
        how_it_guides_plan="If high, focus less on building bathrooms and more on maintenance, drainage and inspection around bathrooms, pipes, drains and septic areas.",
        dengue_relevance="indirect",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "exist_estrut_perc_ald_sem_estrutura": FieldInterpretation(
        field_name="exist_estrut_perc_ald_sem_estrutura",
        group="sewage and sanitation infrastructure",
        priority="very_high",
        why_it_matters="Indicates absence of basic sanitation structure.",
        how_it_guides_plan="Treat as a social vulnerability marker. Include emergency sanitation mapping, safe toilet access and environmental health actions.",
        dengue_relevance="vulnerability",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "exist_estrut_perc_ald_coleta_pela_rede_publica": FieldInterpretation(
        field_name="exist_estrut_perc_ald_coleta_pela_rede_publica",
        group="sewage and sanitation infrastructure",
        priority="high",
        why_it_matters="Shows whether public sewage collection exists.",
        how_it_guides_plan="If present, municipality or concessionaire becomes an important actor. If low, consider decentralized/local solutions.",
        dengue_relevance="governance",
        is_direct_dengue_risk=False,
        is_governance_field=True
    ),
    "exist_estrut_perc_ald_coleta_pela_rede_sesai": FieldInterpretation(
        field_name="exist_estrut_perc_ald_coleta_pela_rede_sesai",
        group="sewage and sanitation infrastructure",
        priority="high",
        why_it_matters="Shows whether SESAI/DSEI infrastructure is involved.",
        how_it_guides_plan="Assign responsibility to Indigenous health sanitation structures where applicable.",
        dengue_relevance="governance",
        is_direct_dengue_risk=False,
        is_governance_field=True
    ),
    "exist_estrut_perc_ald_melhorias_sanits_domic_mds_indiv_coletiv": FieldInterpretation(
        field_name="exist_estrut_perc_ald_melhorias_sanits_domic_mds_indiv_coletiv",
        group="sewage and sanitation infrastructure",
        priority="medium_high",
        why_it_matters="Indicates household or collective sanitation improvements.",
        how_it_guides_plan="Decide whether interventions should upgrade existing structures or start with basic implementation.",
        dengue_relevance="vulnerability",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "est_conserv_estrut_perc_ald_estrut_exist_regular": FieldInterpretation(
        field_name="est_conserv_estrut_perc_ald_estrut_exist_regular",
        group="sewage and sanitation infrastructure",
        priority="very_high",
        why_it_matters="Shows infrastructure exists but may not be ideal.",
        how_it_guides_plan="Trigger inspection and preventive maintenance, especially before rainy periods.",
        dengue_relevance="indirect",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "est_conserv_estrut_perc_ald_estrut_exist_insatisfatoria": FieldInterpretation(
        field_name="est_conserv_estrut_perc_ald_estrut_exist_insatisfatoria",
        group="sewage and sanitation infrastructure",
        priority="very_high",
        why_it_matters="Signals poor condition.",
        how_it_guides_plan="Prioritize villages where infrastructure may fail, leak, overflow, generate stagnant water or create unsafe environments.",
        dengue_relevance="indirect",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "est_conserv_estrut_perc_ald_estrut_exist_requer_manutencao": FieldInterpretation(
        field_name="est_conserv_estrut_perc_ald_estrut_exist_requer_manutencao",
        group="sewage and sanitation infrastructure",
        priority="very_high",
        why_it_matters="Directly indicates maintenance need.",
        how_it_guides_plan="Generate concrete actions: technical visit, repair schedule, cleaning, drainage correction and monitoring.",
        dengue_relevance="indirect",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "est_conserv_estrut_perc_ald_estrut_exist_requer_interd_subst": FieldInterpretation(
        field_name="est_conserv_estrut_perc_ald_estrut_exist_requer_interd_subst",
        group="sewage and sanitation infrastructure",
        priority="very_high",
        why_it_matters="Indicates critical structures that may need interdiction or replacement.",
        how_it_guides_plan="Trigger urgent technical evaluation and temporary alternatives for families.",
        dengue_relevance="vulnerability",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "tipo_trat_esgoto_perc_ald_sem_informacao": FieldInterpretation(
        field_name="tipo_trat_esgoto_perc_ald_sem_informacao",
        group="sewage and sanitation infrastructure",
        priority="very_high",
        why_it_matters="Missing treatment information is a major planning gap.",
        how_it_guides_plan="First intervention should be local validation: what treatment exists, where sewage goes, whether there are leaks, overflow points or stagnant water.",
        dengue_relevance="data_quality",
        is_direct_dengue_risk=False,
        is_governance_field=False,
        requires_local_validation_when_missing=True
    ),
    "tipo_trat_esgoto_perc_ald_sem_tratamento": FieldInterpretation(
        field_name="tipo_trat_esgoto_perc_ald_sem_tratamento",
        group="sewage and sanitation infrastructure",
        priority="high",
        why_it_matters="Indicates environmental and health vulnerability.",
        how_it_guides_plan="Generate structural sanitation actions, environmental inspection and coordination with municipality/SESAI.",
        dengue_relevance="vulnerability",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "tipo_trat_esgoto_perc_ald_destinacao_nos_corpos_hidricos": FieldInterpretation(
        field_name="tipo_trat_esgoto_perc_ald_destinacao_nos_corpos_hidricos",
        group="sewage and sanitation infrastructure",
        priority="medium_high",
        why_it_matters="Indicates sewage disposal into water bodies.",
        how_it_guides_plan="Treat as more relevant for water contamination and environmental health than dengue directly.",
        dengue_relevance="not_direct",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "tipo_trat_esgoto_perc_ald_tratamento_por_fossa_rudimentar": FieldInterpretation(
        field_name="tipo_trat_esgoto_perc_ald_tratamento_por_fossa_rudimentar",
        group="sewage and sanitation infrastructure",
        priority="medium_high",
        why_it_matters="Rudimentary systems can be vulnerable to overflow, poor sealing and maintenance issues.",
        how_it_guides_plan="Generate inspection and upgrade recommendations, especially if combined with rainfall and poor conservation.",
        dengue_relevance="indirect",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "tipo_trat_esgoto_perc_ald_tratamento_por_fossa_sumidouro": FieldInterpretation(
        field_name="tipo_trat_esgoto_perc_ald_tratamento_por_fossa_sumidouro",
        group="sewage and sanitation infrastructure",
        priority="medium",
        why_it_matters="Indicates decentralized sanitation.",
        how_it_guides_plan="Use for maintenance planning and inspection of overflow, infiltration and nearby stagnant water.",
        dengue_relevance="indirect",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "tipo_trat_esgoto_perc_ald_tratamento_por_fossa_filtro_sumidouro": FieldInterpretation(
        field_name="tipo_trat_esgoto_perc_ald_tratamento_por_fossa_filtro_sumidouro",
        group="sewage and sanitation infrastructure",
        priority="medium",
        why_it_matters="Indicates more structured decentralized treatment.",
        how_it_guides_plan="If present and well maintained, focus on monitoring rather than replacement.",
        dengue_relevance="indirect",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "tipo_trat_esgoto_perc_ald_tratamento_por_fossa_seca": FieldInterpretation(
        field_name="tipo_trat_esgoto_perc_ald_tratamento_por_fossa_seca",
        group="sewage and sanitation infrastructure",
        priority="medium",
        why_it_matters="Indicates dry sanitation solution.",
        how_it_guides_plan="Use for dignity, safety and maintenance planning; less directly related to dengue unless associated with water accumulation nearby.",
        dengue_relevance="not_direct",
        is_direct_dengue_risk=False,
        is_governance_field=False
    ),
    "tipo_trat_esgoto_perc_ald_atendidas_por_concessionaria": FieldInterpretation(
        field_name="tipo_trat_esgoto_perc_ald_atendidas_por_concessionaria",
        group="sewage and sanitation infrastructure",
        priority="high",
        why_it_matters="Identifies formal service provider involvement.",
        how_it_guides_plan="Assign action to concessionaire or municipality instead of placing burden only on the village.",
        dengue_relevance="governance",
        is_direct_dengue_risk=False,
        is_governance_field=True
    ),
}

# Add water supply and epidemiological notification groups similarly
WATER_SUPPLY_FIELDS = [
    "populacao_total", "numero_de_aldeias", "_aldeias_com_infraestrutura", "pop_total_com_infraestrutura_de_abastecimento",
    "soma_de_infraestrutura_saasac", "satisfatorio__aldeia", "satisfatorio_pop", "requer_manutencao__aldeia",
    "requer_manutencao_pop", "requer_substituicao__aldeia", "requer_substituicao_pop", "_aldeia_abastecimento_caminhao_pipa",
    "pop_total_abastecimento_por_caminhao_pipa", "_aldeia_sem_fornecimento", "pop_sem_fornecimento",
    "_de_aldeias_monitoradas_em_relacao_ao_total", "_de_aldeias_monitoradas_em_relacao_ao_pmqai_planejado",
    "n_aldeias_pmqai", "media_do_numero_de_aldeias_monitoradas_no_mes_com_analise_dos_6", "sem_info_pop", "sem_info__aldeia"
]

for field in WATER_SUPPLY_FIELDS:
    CATALOG[field] = FieldInterpretation(
        field_name=field,
        group="water supply and monitoring",
        priority="medium_high",
        why_it_matters="Water supply indicators",
        how_it_guides_plan="High percentage of villages without water supply is a vulnerability marker. Relevant if it implies unsafe domestic water storage.",
        dengue_relevance="vulnerability",
        is_direct_dengue_risk=True if "caminhao_pipa" in field or "sem_fornecimento" in field else False,
        is_governance_field=False,
        requires_local_validation_when_missing=True if "sem_info" in field else False
    )

EPI_FIELDS = {
    "id_agravo": ("Disease identification", "very_high"),
    "arquivo": ("Disease identification", "very_high"),
    "tp_not": ("Disease identification", "very_high"),
    "dt_notific": ("Notification time", "very_high"),
    "sem_not": ("Notification time", "very_high"),
    "nu_ano": ("Notification time", "very_high"),
    "dt_digita": ("Notification time", "very_high"),
    "dt_sin_pri": ("Symptom onset time", "very_high"),
    "sem_pri": ("Symptom onset time", "very_high"),
    "dt_invest": ("Investigation and closure", "very_high"),
    "dt_encerra": ("Investigation and closure", "very_high"),
    "classi_fin": ("Investigation and closure", "very_high"),
    "criterio": ("Investigation and closure", "very_high"),
    "sg_uf_not": ("Place of notification", "high"),
    "id_municip": ("Place of notification", "high"),
    "id_regiona": ("Place of notification", "high"),
    "id_unidade": ("Place of notification", "high"),
    "sg_uf": ("Place of residence", "very_high"),
    "id_mn_resi": ("Place of residence", "very_high"),
    "id_rg_resi": ("Place of residence", "very_high"),
    "id_pais": ("Place of residence", "very_high"),
    "tpautocto": ("Probable place of infection", "very_high"),
    "coufinf": ("Probable place of infection", "very_high"),
    "copaisinf": ("Probable place of infection", "very_high"),
    "comuninf": ("Probable place of infection", "very_high"),
    "nu_idade_n": ("Demographics", "high"),
    "ano_nasc": ("Demographics", "high"),
    "cs_sexo": ("Demographics", "high"),
    "cs_gestant": ("Demographics", "high"),
    "cs_raca": ("Demographics", "high"),
    "cs_escol_n": ("Demographics", "high"),
    "febre": ("Symptoms", "medium_high"),
    "mialgia": ("Symptoms", "medium_high"),
    "cefaleia": ("Symptoms", "medium_high"),
    "exantema": ("Symptoms", "medium_high"),
    "vomito": ("Symptoms", "medium_high"),
    "nausea": ("Symptoms", "medium_high"),
    "dor_costas": ("Symptoms", "medium_high"),
    "conjuntvit": ("Symptoms", "medium_high"),
    "artrite": ("Symptoms", "medium_high"),
    "artralgia": ("Symptoms", "medium_high"),
    "petequia_n": ("Symptoms", "medium_high"),
    "leucopenia": ("Symptoms", "medium_high"),
    "laco": ("Symptoms", "medium_high"),
    "dor_retro": ("Symptoms", "medium_high"),
    "diabetes": ("Comorbidities", "high"),
    "hematolog": ("Comorbidities", "high"),
    "hepatopat": ("Comorbidities", "high"),
    "renal": ("Comorbidities", "high"),
    "hipertensa": ("Comorbidities", "high"),
    "acido_pept": ("Comorbidities", "high"),
    "auto_imune": ("Comorbidities", "high"),
    "alrm_hipot": ("Warning signs", "very_high"),
    "alrm_plaq": ("Warning signs", "very_high"),
    "alrm_vom": ("Warning signs", "very_high"),
    "alrm_sang": ("Warning signs", "very_high"),
    "alrm_hemat": ("Warning signs", "very_high"),
    "alrm_abdom": ("Warning signs", "very_high"),
    "alrm_letar": ("Warning signs", "very_high"),
    "alrm_hepat": ("Warning signs", "very_high"),
    "alrm_liq": ("Warning signs", "very_high"),
    "dt_alrm": ("Warning signs", "very_high"),
    "grav_pulso": ("Severe signs", "very_high"),
    "grav_conv": ("Severe signs", "very_high"),
    "grav_ench": ("Severe signs", "very_high"),
    "grav_insuf": ("Severe signs", "very_high"),
    "grav_taqui": ("Severe signs", "very_high"),
    "grav_extre": ("Severe signs", "very_high"),
    "grav_hipot": ("Severe signs", "very_high"),
    "grav_hemat": ("Severe signs", "very_high"),
    "grav_melen": ("Severe signs", "very_high"),
    "grav_metro": ("Severe signs", "very_high"),
    "grav_sang": ("Severe signs", "very_high"),
    "grav_ast": ("Severe signs", "very_high"),
    "grav_mioc": ("Severe signs", "very_high"),
    "grav_consc": ("Severe signs", "very_high"),
    "grav_orgao": ("Severe signs", "very_high"),
    "dt_grav": ("Severe signs", "very_high"),
    "mani_hemor": ("Hemorrhagic or plasma leakage fields", "high"),
    "epistaxe": ("Hemorrhagic or plasma leakage fields", "high"),
    "gengivo": ("Hemorrhagic or plasma leakage fields", "high"),
    "metro": ("Hemorrhagic or plasma leakage fields", "high"),
    "petequias": ("Hemorrhagic or plasma leakage fields", "high"),
    "hematura": ("Hemorrhagic or plasma leakage fields", "high"),
    "sangram": ("Hemorrhagic or plasma leakage fields", "high"),
    "laco_n": ("Hemorrhagic or plasma leakage fields", "high"),
    "plasmatico": ("Hemorrhagic or plasma leakage fields", "high"),
    "evidencia": ("Hemorrhagic or plasma leakage fields", "high"),
    "plaq_menor": ("Hemorrhagic or plasma leakage fields", "high"),
    "con_fhd": ("Hemorrhagic or plasma leakage fields", "high"),
    "complica": ("Hemorrhagic or plasma leakage fields", "high"),
    "dt_soro": ("Laboratory testing", "high"),
    "resul_soro": ("Laboratory testing", "high"),
    "dt_viral": ("Laboratory testing", "high"),
    "resul_vi_n": ("Laboratory testing", "high"),
    "sorotipo": ("Laboratory testing", "high"),
    "dt_pcr": ("Laboratory testing", "high"),
    "resul_pcr_": ("Laboratory testing", "high"),
    "dt_ns1": ("Laboratory testing", "high"),
    "resul_ns1": ("Laboratory testing", "high"),
    "imunoh_n": ("Laboratory testing", "high"),
    "histopa_n": ("Laboratory testing", "high"),
    "hospitaliz": ("Hospitalization and outcome", "very_high"),
    "dt_interna": ("Hospitalization and outcome", "very_high"),
    "evolucao": ("Hospitalization and outcome", "very_high"),
    "dt_obito": ("Hospitalization and outcome", "very_high"),
    "nduplic_n": ("Data quality and duplicate control", "very_high"),
    "nduplic": ("Data quality and duplicate control", "very_high"),
    "flxrecebi": ("Data quality and duplicate control", "very_high"),
    "migrado_w": ("Data quality and duplicate control", "very_high"),
}

for field, (group, priority) in EPI_FIELDS.items():
    CATALOG[field] = FieldInterpretation(
        field_name=field,
        group=group,
        priority=priority,
        why_it_matters=f"Epidemiological field: {field}",
        how_it_guides_plan="Used to understand the epidemiological profile and severity of the situation.",
        dengue_relevance="clinical",
        is_direct_dengue_risk=False,
        is_governance_field=False
    )
